In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [6]:
x1 = np.array(l)

In [4]:
l2 = [4,5,6,7]

In [7]:
x2 = np.array(l2)

In [9]:
x1 + x2 # elementwise addition

array([ 5,  7,  9, 11])

In [10]:
print(np.array(3).shape)
print(np.array([3]).shape)
print(np.array([[3]]).shape)
print(np.array([[[3]]]).shape)

()
(1,)
(1, 1)
(1, 1, 1)


In [11]:
import time as time

x_list=[i for i in range(100000)]

x=np.array(x_list)

st=time.process_time()

x_list=[i+10 for i in x_list]
ed=time.process_time()


print(round(ed-st,5))


st=time.process_time()

x+=10

ed=time.process_time()

print(round(ed-st,5))

0.00796
0.00033


In [13]:
x=np.array([1,2,3,4])


print(type(x))


print(x[0],x[1],x[2],x[3])


x[1]=x[2]


print(x)


print(x.shape)

<class 'numpy.ndarray'>
1 2 3 4
[1 3 3 4]
(4,)


In [23]:
x=np.random.random((4,3))


x.shape

x2 = np.transpose(x)

x2.shape

print(x2)

[[0.82672143 0.37589787 0.19540882 0.66782775]
 [0.52309343 0.91059971 0.71711256 0.58937829]
 [0.48436437 0.94334207 0.81011224 0.7689495 ]]


In [30]:
x=np.array([[1,2,3,4],[4,5,6,7]])

print(x)

x2 = np.transpose(x)

print(x2)

[[1 2 3 4]
 [4 5 6 7]]
[[1 4]
 [2 5]
 [3 6]
 [4 7]]
