In [89]:
import numpy as np

x1=np.linspace(0,5,5)
x2=np.linspace(0,5,5)

In [90]:
[X1,X2]=np.meshgrid(x1,x2)

In [91]:
X1

array([[0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ],
       [0.  , 1.25, 2.5 , 3.75, 5.  ]])

In [92]:
X2

array([[0.  , 0.  , 0.  , 0.  , 0.  ],
       [1.25, 1.25, 1.25, 1.25, 1.25],
       [2.5 , 2.5 , 2.5 , 2.5 , 2.5 ],
       [3.75, 3.75, 3.75, 3.75, 3.75],
       [5.  , 5.  , 5.  , 5.  , 5.  ]])

In [93]:
X1_t = np.reshape(X1, (X1.shape[0]*X1.shape[1]))
X2_t = np.reshape(X2, (X2.shape[0]*X2.shape[1]))

In [95]:
X1_t.shape

(25,)

In [105]:
X = []

nb = 0

for i in range(nb+1):

    for j in range(nb+1):
        print(X1_t**i)
        print(X1_t**i * X2_t**j)
        # X.append(X1_t**i * X2_t**j)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]


In [107]:
X1_t * X1_t

array([ 0.    ,  1.5625,  6.25  , 14.0625, 25.    ,  0.    ,  1.5625,
        6.25  , 14.0625, 25.    ,  0.    ,  1.5625,  6.25  , 14.0625,
       25.    ,  0.    ,  1.5625,  6.25  , 14.0625, 25.    ,  0.    ,
        1.5625,  6.25  , 14.0625, 25.    ])